### ISSUE TITLE
How to find unformatted Numbers

### ISSUE THREAD

**Issue by signalwerk** [uberbruns/PhoneNumbers#2]
First of all: Great app! Thx to mm and your work I'm able to clean my numbers!
I have a suggestion for the GUI: I would like to format my numbers with the tool but right now it's a bit tricky. I have a lot of Numbers in my adress book and I would like to hide the numbers witch have already the correct format. 

Example:
+41 79 777 77 77 gets converted to +41 79 777 77 77 (same)

So it would be really helpful to show only «wrong» numbers. Because just there I have to do something and be careful when I do convert. A checkbox like «Show only non-conform numbers» would help a lot.

**Comment by uberbruns** [comment]
Nice Suggestion! I'll look into it. 
—

**Comment by signalwerk** [comment]
#yay! Thanks a lot
